[package]
name = "efron_numbertheory"
version = "0.3.1"
authors = ["efron_licht <efron.python@gmail.com>"]
license="MIT"
description="a library for basic number theory"
[dependencies]
maplit = "1.0.1"